var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                    xxvxx                        xxvxx                         ",
   "x                                                                               ",
   "x                                                                               ",
   "x                                                                               ",
   "x                                                                  o     o      ",
   "x            o o                                        o  o                    ",
   "x                                                                 xxxxxxxxx     ",
   "x           xxxxx                                      xxxxxx                   ",
   "x                                            xbxxx                              ",
   "x                    xxxxx                                                    s ",
   "x                             xxppxx     xxxxxxxxxxx                         xxx",
   "x                             xxxxxx!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "xxx                   xxxxx   xxxxxx!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "xxx                           xxxxxx!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "xxx             xxxx          xxxxxx!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "xxx  @                      o xxxxxx!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "xxxxxrxxx   xxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "xxxxxxxxx   xxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "xxxxxxxxx!!!xxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "xxxxxxxxx!!!xxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ["                    ",
   "                     ",
   "                     ",
   "          xxxxx      ",
   "              x      ",
   "              x      ",
   "          xxxxx      ",
   "          x          ",
   "          x          ",
   "          xxxxx      ",
   "   @               s ",
   "xxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "          xvvx                        xvvx                                    x                                xxx",
   "                                                                              x                                xxx",
   "                                                                      xx      x                   o         s  xxx",
   "                                                                      xx  |   x                                xxx",
   "                                                                     xxx      x                    x   x   x  xxxx",
   "                                                                      xx      x                x!!!!!!!!!!!!!!!xxx",
   "                                                                      xx      x        xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                 o    xx      x        xvx                        ",
   "                                                                xxx   xx      x                o      o      o    ",
   "                                    x                                 xx      x                                   ",
   "                                    x                                 xx      xxxxxx         xxxxxxxxxxxxxxxxxxxx ",
   "                                    x                        o        xx           x         xxxxxxxxxxxxxxxxxxxx ",
   "                                    x                       xxx    xpxxx           x      xxxxxxxxxxxxxxxxxxxxxxx ",
   "                                    x                               xxxxx          x         xxxxxxxxxxxxxxxxxxxx ",
   "                                    x                               xxxxxx         x         xxxxxxxxxxxxxxxxxxxx ",
   "                             xxxx   x                               xxxxxx     o o xx        xxxxxxxxxxxxxxxxxxxx ",
   "              xxxxxxxxx       xx    x                              xxxxxxx   xxxxxxx         xxxxxxxxxxxxxxxxxxxx ",
   "                      xx      xxx o x                               xxxxxx                   xxxxxxxxxxxxxxxxxxxx ",
   "     @                 x      xx    x                               xxxxx     o    o      xxxxxxxxxxxxxxxxxxxxxxx ",
   "    xrxxx    xxx       x      xx    x                     x  =      xxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxx ",
   "xx xx x        xxx     x      xxx o xb    x               xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxx!",
   "xx xx x!!!!!!!!!!xx    x!!!!!!xx    xxx!!!x!!!!xx     x!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxx!",
   "xxoxx x!!!!!!!!!!x     x!!!!!xx      xxxxxxxxxxx     x!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxx!",
   "xxxxx x!!!!!!!!!!x     x!!!!!x    o                 xx!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxx!",
   "xxxxx x!!!!!!!!!!x    xx!!!!!x                     xx!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!",
   "xxxxx x!!!!!!!!!!x     x!!!!!xx       xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx x!!!!!!!!!!x o o x!!!!!!xxx!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx x!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ["                    ",
   "                     ",
   "                     ",
   "          xxxxx      ",
   "              x      ",
   "              x      ",
   "          xxxxx      ",
   "              x      ",
   "              x      ",
   "          xxxxx      ",
   "   @               s ",
   "xxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxvxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                       ooo                                                                                    ",
   "                     xxxxxxx                                                                                  ",
   "                    =               xxx  =                                                                    ",
   "                                                                                                              ",
   "                                                    o      o                                                  ",
   "                                                                                                              ",
   "                                                  xxpppppppppxx                                               ",
   "          oo                                      xxxxxxxxxxxxx                                 =             ",
   "        xxxxxxxxxx                                xxxxxxxxxxxxx                                               ",
   "                                                  xxxxxxxxxxxxx                                               ",
   "            =                    =                xxxxxxxxxxxxx             xxx                s              ",
   "                            oo                    xxxxxxxxxxxxx                                               ",
   "                     xxxxxxxxxxx                  xxxxxxxxxxxxx                           xxxxxxxxxx          ",
   "                                                  xxxxxxxxxxxxx                                               ",
   "                                                  xxxxxxxxxxxxx                                               ",
   "        o o                                       xxxxxxxxxxxxx                                               ",
   "      xxxxxxxxxxx                    xxxx         xxxxxxxxxxxxx                                 =             ",
   "                                                  xxxxxxxxxxxxx                                               ",
   "                                                      xxxxxxxxx                                               ",
   "                                                 o o  xxxxxxxxx                                               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   =      xxxxxxxxxxxxxxxxxxxxx                                   ",
   "                             xx           xx     xxxxxxxxxxxxxxxxxxxxxxxxxx                                   ",
   "   @                         xx  o        xxxx                                                                ",
   "  xrx                    xxxxxxxxxxx                          =         =                                     ",
   "  xxxxxxxxxxxxxxxxxx         xx    x                                                                          ",
   "  xxxxxxxxxxxxvxxxxx          xx   x     xxxxxxxx           xxxxxxxxxxxxxxxxxxx                               ",
   "  x  v  vxxxx              | o x        xxxxxxxxx                        xxxxxx                               ",
   "!!x       xx  o      xxxxxxxxxxx          xxxxxxxxx             o        xxxxxx      x                        ",
   "!!xo      xxxxxxx                         x              xxx          xxxxxxxxx             xbx               ",
   "!!xx      xx                        xx    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!x                             xx        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!xo                               o      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!xx|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                    ",
   "                                                                    ",
   "                                                                    ",
   "                                                                    ",
   "                                                                    ",
   "                                                                    ",
   "                            x                                       ",
   "                                                                    ",
   "              x           x x   xx    x xx    x xxx xxxx            ",
   "               x    x    x  x   x x   x x x   x x   x  x            ",
   "                x  xxx  x   x   x  x  x x  x  x xxx xxx             ",
   "                 xxx xxx    x   x   x x x   x x x   x  x            ",
   "                  x   x     x   x    xx x    xx xxx x   x           ",
   "                                                                    ",
   "                                                                    ",
   "                                                                    ",
   "    @                                                               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
